[versions]
detekt = "1.23.8"
kotlin = "2.2.0"
ktlintGradle = "13.0.0"
pluginPublish = "1.3.1"
versionCheck = "0.52.0"
autonomousapps-testkit = "0.14"
junit = "5.13.4"
publish="0.34.0"
agp = "8.7.3"
jackson = "2.19.2"
plist-reader = "1.28"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle"}
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish"}
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck"}
autonomousapps-testkit = { id = "com.autonomousapps.testkit", version.ref = "autonomousapps-testkit" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform" }

[libraries]
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
plist-reader = { module = "com.googlecode.plist:dd-plist", version.ref = "plist-reader"}
